Repository ManageIQ/manageiq-providers-openshift, pull requests merged in 2018-08, with the labels that each got.

#104 Switch to proper targeted refresh
  app/models/manageiq/providers/openshift/inventory/persister/target_collection.rb
Labels: enhancement, gaprindashvili/no, inventory

#107 Add plugin display name
  lib/manageiq/providers/openshift/engine.rb
Labels: enhancement, gaprindashvili/no

#108 Move Inventory to ManageIQ::Providers
  app/models/manageiq/providers/openshift/inventory/persister.rb
Labels: refactoring

#106 Refresh service catalog entities specs
  app/models/manageiq/providers/openshift/container_manager/service_offering.rb
  app/models/manageiq/providers/openshift/container_manager/service_parameters_set.rb
  spec/models/manageiq/providers/openshift/container_manager/refresher_inventory_object_spec.rb
  spec/vcr_cassettes/manageiq/providers/openshift/container_manager/refresher_inventory_object.yml
Labels: test

#109 [Changelog] Update for Sprint 93
  CHANGELOG.md
Labels: documentation

#110 Fix a reference to ManagerRefresh::Inventory
  spec/models/manageiq/providers/openshift/container_manager/refresher_inventory_object_spec.rb
Labels: refactoring
