Repository ManageIQ/manageiq-providers-openshift, pull requests merged in 2018-09, with the labels that each got.

#114 Fix specs failing on a missing zone
  spec/factories/ext_management_system.rb
  spec/models/manageiq/providers/openshift/container_manager/container_template_spec.rb
  spec/models/manageiq/providers/openshift/container_manager/refresher_inventory_object_spec.rb
  spec/models/manageiq/providers/openshift/container_manager/refresher_spec.rb
  spec/models/manageiq/providers/openshift/container_manager/targeted_refresh/targeted_refresh_spec.rb
Labels: test

#113 Updates for streaming service catalog
  app/models/manageiq/providers/openshift/container_manager/refresh_worker/runner.rb
Labels: enhancement

#118 [Changelog] Update for Sprint 95
  CHANGELOG.md
Labels: documentation
