Repository ManageIQ/manageiq-providers-openshift, pull requests merged in 2018-07, with the labels that each got.

#101 ContainerImage archivation
  spec/models/manageiq/providers/openshift/container_manager/refresher_spec.rb
Labels: inventory, test

#100 Persister: InventoryCollection building through add_collection()
  app/models/manageiq/providers/openshift/inventory/persister.rb
  app/models/manageiq/providers/openshift/inventory/persister/container_manager.rb
  app/models/manageiq/providers/openshift/inventory/persister/target_collection.rb
Labels: enhancement

#102 [Changelog] Update for Sprint 90
  CHANGELOG.md
Labels: documentation
