Repository ManageIQ/manageiq-providers-openshift, pull requests merged in 2019-11, with the labels that each got.

#151 Remove from README
  README.md
Labels: cleanup

#152 Remove unused InventoryCollectorWorker
  app/models/manageiq/providers/openshift/container_manager.rb
  app/models/manageiq/providers/openshift/container_manager/inventory_collector_worker.rb
  app/models/manageiq/providers/openshift/container_manager/inventory_collector_worker/runner.rb
  config/settings.yml
Labels: cleanup

#153 Optionally symlink spec/manageiq during bin/setup
  bin/setup
Labels: enhancement

#156 Rely on the default implementation of .ems_class
  app/models/manageiq/providers/openshift/container_manager/event_catcher.rb
  app/models/manageiq/providers/openshift/container_manager/metrics_collector_worker.rb
  app/models/manageiq/providers/openshift/container_manager/refresh_worker.rb
  app/models/manageiq/providers/openshift/monitoring_manager/event_catcher.rb
Labels: refactoring
