Repository ManageIQ/manageiq-providers-openshift, pull requests merged in 2019-01, with the labels that each got.

#130 Remove duplicated persister shared_options
  app/models/manageiq/providers/openshift/inventory/persister/container_manager.rb
Labels: refactoring

#131 Change FactoryGirl to FactoryBot
  spec/factories/container_image.rb
  spec/factories/ext_management_system.rb
  spec/factories/openshift_template.rb
  spec/models/manageiq/providers/openshift/container_manager/container_image_spec.rb
  spec/models/manageiq/providers/openshift/container_manager/container_template_spec.rb
  spec/models/manageiq/providers/openshift/container_manager/orchestration_stack_spec.rb
  spec/models/manageiq/providers/openshift/container_manager/refresher_inventory_object_spec.rb
  spec/models/manageiq/providers/openshift/container_manager/refresher_spec.rb
  spec/models/manageiq/providers/openshift/container_manager/targeted_refresh/targeted_refresh_spec.rb
  spec/models/manageiq/providers/openshift/container_manager_spec.rb
Labels: gaprindashvili/no, hammer/no, test

#132 [Changelog] Update for Hammer-1
  CHANGELOG.md
Labels: documentation
