Repository ManageIQ/manageiq-providers-openshift, pull requests merged in 2020-05, with the labels that each got.

#170 Container routes always belong to the EMS
  app/models/manageiq/providers/openshift/container_manager_mixin.rb
Labels: bug

#169 Use watches for targeted refresh
  app/models/manageiq/providers/openshift/container_manager/refresh_worker.rb
  app/models/manageiq/providers/openshift/container_manager/refresh_worker/runner.rb
  app/models/manageiq/providers/openshift/container_manager/refresh_worker/watch_thread.rb
  app/models/manageiq/providers/openshift/container_manager_mixin.rb
  app/models/manageiq/providers/openshift/inventory/collector.rb
  app/models/manageiq/providers/openshift/inventory/collector/container_manager.rb
  app/models/manageiq/providers/openshift/inventory/collector/watch_notice.rb
  app/models/manageiq/providers/openshift/inventory/parser.rb
  app/models/manageiq/providers/openshift/inventory/parser/container_manager.rb
  app/models/manageiq/providers/openshift/inventory/parser/openshift_parser_mixin.rb
  app/models/manageiq/providers/openshift/inventory/parser/watch_notice.rb
  app/models/manageiq/providers/openshift/inventory/persister.rb
  app/models/manageiq/providers/openshift/inventory/persister/watch_notice.rb
  config/settings.yml
  spec/models/manageiq/providers/openshift/container_manager/refresher_spec.rb
  spec/models/manageiq/providers/openshift/container_manager/watches_data/build.yml
  spec/models/manageiq/providers/openshift/container_manager/watches_data/build_config.yml
  spec/models/manageiq/providers/openshift/container_manager/watches_data/image.yml
  spec/models/manageiq/providers/openshift/container_manager/watches_data/new_build.yml
  spec/models/manageiq/providers/openshift/container_manager/watches_data/new_build_config.yml
  spec/models/manageiq/providers/openshift/container_manager/watches_data/new_project.yml
  spec/models/manageiq/providers/openshift/container_manager/watches_data/new_route.yml
  spec/models/manageiq/providers/openshift/container_manager/watches_data/new_template.yml
  spec/models/manageiq/providers/openshift/container_manager/watches_data/project.yml
  spec/models/manageiq/providers/openshift/container_manager/watches_data/route.yml
  spec/models/manageiq/providers/openshift/container_manager/watches_data/template.yml
Labels: enhancement, jansa/yes?, performance

#172 Add a method to detect the metrics service hostname
  app/models/manageiq/providers/openshift/container_manager_mixin.rb
Labels: refactoring

#174 Add metrics/alerts hostname detection on OCP v4
  app/models/manageiq/providers/openshift/container_manager_mixin.rb
Labels: enhancement, jansa/yes?

#175 Fix README to point to travis-ci.com instead of travis-ci.org
  README.md
Labels: bug, developer

#176 Removing deprecated Gemnasium badge
  README.md
Labels: developer

#179 V4 openshift-monitoring/alertmanager-main isn't the PrometheusAlertBuffer
  app/models/manageiq/providers/openshift/container_manager_mixin.rb
Labels: bug, jansa/yes?
