Repository ManageIQ/manageiq-providers-openshift, pull requests merged in 2020-10, with the labels that each got.

#191 Test with ruby 2.5.8 and 2.6.6
  .travis.yml
Labels: test

#181 Switch to manageiq-style
  .codeclimate.yml
  .rubocop.yml
  .rubocop_cc.yml
  manageiq-providers-openshift.gemspec
Labels: unmergeable

#192 Fix .rubocop_local.yml
  .rubocop_local.yml
Labels: developer

#193 [KASPAROV] Test with ruby 2.6.6 on Kasparov
  .travis.yml
Labels: test

#195 [JANSA] Test with ruby 2.6.6 on Jansa
  .travis.yml
Labels: test
