Repository ManageIQ/manageiq-providers-openshift, pull requests merged in 2024-09, with the labels that each got.

#264 Subclass Kubevirt InfraManager to separate Openshift Virtualization provider
  app/assets/images/svg/vendor-openshift_infra.svg
  app/models/manageiq/providers/openshift/container_manager.rb
  app/models/manageiq/providers/openshift/infra_manager.rb
  app/models/manageiq/providers/openshift/infra_manager/cluster.rb
  app/models/manageiq/providers/openshift/infra_manager/connection.rb
  app/models/manageiq/providers/openshift/infra_manager/host.rb
  app/models/manageiq/providers/openshift/infra_manager/provision.rb
  app/models/manageiq/providers/openshift/infra_manager/provision_workflow.rb
  app/models/manageiq/providers/openshift/infra_manager/refresh_worker.rb
  app/models/manageiq/providers/openshift/infra_manager/refresh_worker/runner.rb
  app/models/manageiq/providers/openshift/infra_manager/refresher.rb
  app/models/manageiq/providers/openshift/infra_manager/storage.rb
  app/models/manageiq/providers/openshift/infra_manager/template.rb
  app/models/manageiq/providers/openshift/infra_manager/vm.rb
  app/models/manageiq/providers/openshift/inventory.rb
  app/models/manageiq/providers/openshift/inventory/collector/infra_manager.rb
  app/models/manageiq/providers/openshift/inventory/parser/infra_manager.rb
  app/models/manageiq/providers/openshift/inventory/parser/infra_manager/full_refresh.rb
  app/models/manageiq/providers/openshift/inventory/parser/infra_manager/partial_refresh.rb
  app/models/manageiq/providers/openshift/inventory/parser/infra_manager/partial_target_refresh.rb
  app/models/manageiq/providers/openshift/inventory/persister/infra_manager.rb
  config/settings.yml
  spec/factories/ext_management_system.rb
  spec/models/manageiq/providers/openshift/infra_manager/refresher_spec.rb
  spec/vcr_cassettes/manageiq/providers/openshift/infra_manager/refresher.yml
  systemd/manageiq-providers-openshift_infra_manager_refresh.target
  systemd/manageiq-providers-openshift_infra_manager_refresh@.service
Labels: enhancement, wip, radjabov/yes?

#266 Openshift Virtualization Service Catalog Support
  app/models/manageiq/providers/openshift/infra_manager/provision_workflow.rb
  content/miq_dialogs/miq_provision_openshift_dialogs_template.yaml
Labels: enhancement, radjabov/yes?

#268 Fix full refresh error when running a RefreshWorker
  app/models/manageiq/providers/openshift/infra_manager/refresh_memory.rb
Labels: bug, radjabov/yes?

#269 Fix refresh worker partial refresh error
  app/models/manageiq/providers/openshift/infra_manager/refresh_worker/runner.rb
Labels: bug, radjabov/yes?
