Repository ManageIQ/manageiq-providers-openshift, pull requests merged in 2024-02, with the labels that each got.

#253 Drop require_nested
  app/models/manageiq/providers/openshift/container_manager.rb
  app/models/manageiq/providers/openshift/container_manager/event_catcher.rb
  app/models/manageiq/providers/openshift/container_manager/metrics_collector_worker.rb
  app/models/manageiq/providers/openshift/container_manager/orchestration_stack.rb
  app/models/manageiq/providers/openshift/container_manager/refresh_worker.rb
  app/models/manageiq/providers/openshift/inventory.rb
  app/models/manageiq/providers/openshift/inventory/collector.rb
  app/models/manageiq/providers/openshift/inventory/collector/container_manager.rb
  app/models/manageiq/providers/openshift/inventory/parser.rb
  app/models/manageiq/providers/openshift/inventory/parser/container_manager.rb
  app/models/manageiq/providers/openshift/inventory/persister.rb
  app/models/manageiq/providers/openshift/inventory/persister/container_manager.rb
  app/models/manageiq/providers/openshift/monitoring_manager.rb
  app/models/manageiq/providers/openshift/monitoring_manager/event_catcher.rb
Labels: technical debt, rails7

#254 Test with ruby 3.1 and 3.0
  .github/workflows/ci.yaml
Labels: test

#256 [RADJABOV] Test radjabov with ruby 3.1
  .github/workflows/ci.yaml
Labels: test, ruby3.1

#255 drop use of unsupported_reason_add
  app/models/manageiq/providers/openshift/container_manager/container_template.rb
Labels: refactoring, radjabov/yes?
